### ISSUE TITLE
Question about “Geometric-space Aligned Student”

### ISSUE THREAD

**Issue by Rayn-Wu** [liujiaming1996/BEVUDA#1]
Hi, thanks for sharing this great project!
In your paper,  Sec. III (D):
> we project multi-geometric features (i.e., 2D images, Voxel, and BEV) to a shared geometric embedding space and decrease the data distribution distance between two domains.

Could you please show me where is the "projection" part in your code? It would help me alot.

**Comment by liujiaming1996** [comment]
Thank you for your interest in our work. We have documented the projection layer at https://github.com/liujiaming1996/BEVUDA/tree/main/layers/discriminator, where you can find different structures of the projection layer. Of course, the design of the projection layer is not limited to this; we have also followed previous mainstream UDA adversarial work. We hope this can assist you in your research.

**Comment by Rayn-Wu** [comment]
Thank you very much for your reply！
